"""
training_phase/discard.py — Joint preflop + discard alternating training.

Each round:
  1. Build terminal_fn from current discard model
     (preflop CFR uses discard model to evaluate terminal states)
  2. Train preflop CFR using terminal_fn
  3. Generate discard episodes using updated preflop range
  4. Train DiscardNet on generated data

Preflop doesn't import Discard — terminal_fn is the only coupling point,
injected here in training_phase.
"""

from tqdm import tqdm

from deep_cfr_training.stretegy import Preflop
from deep_cfr_training.stretegy import Discard


def _make_terminal_fn(discard_model, preflop_model):
    """
    Returns terminal(h0, h1, state, traverser, rng) that uses discard_model
    (with preflop range) instead of heuristic best_discard.
    Falls back to heuristic if discard net not loaded yet.
    """
    from game.game import DECK_SIZE
    from stretegy.preflop_cfr.train import _get_eval

    def terminal(h0, h1, state, traverser, rng):
        if state.folded_by >= 0:
            winner = 1 - state.folded_by
            gain   = float(min(state.bets))
            return gain if traverser == winner else -gain

        dead      = set(h0) | set(h1)
        remaining = [c for c in range(DECK_SIZE) if c not in dead]
        flop      = rng.sample(remaining, 3)

        if discard_model._net is not None:
            from range_finder.core import Range
            range_obj = Range()
            range_obj.update([], [], [], 'preflop', preflop_model,
                             history=state.hist)
            (ki0, kj0), _ = discard_model.action(
                flop, list(h0), '', range_obj.hero_range, range_obj.opp_range)
            (ki1, kj1), _ = discard_model.action(
                flop, list(h1), '', range_obj.opp_range, range_obj.hero_range)
        else:
            from heuristic.prob_agent import get_heuristic_agent
            heur = get_heuristic_agent()
            ki0, kj0 = heur.best_discard(list(h0), flop)
            ki1, kj1 = heur.best_discard(list(h1), flop)

        kept0 = [h0[ki0], h0[kj0]]
        kept1 = [h1[ki1], h1[kj1]]

        dead_full  = dead | set(flop)
        remaining2 = [c for c in range(DECK_SIZE) if c not in dead_full]
        turn, river = rng.sample(remaining2, 2)
        board = flop + [turn, river]

        ev_obj, itc = _get_eval()
        brd = [itc(c) for c in board]
        s0  = ev_obj.evaluate([itc(c) for c in kept0], brd)
        s1  = ev_obj.evaluate([itc(c) for c in kept1], brd)

        bet = float(min(state.bets))
        if   s0 < s1: winner = 0
        elif s1 < s0: winner = 1
        else:         winner = -1

        if winner == traverser:     return  bet
        if winner == 1 - traverser: return -bet
        return 0.

    return terminal


def train(preflop_model: Preflop, discard_model: Discard,
          n_rounds:        int   = 5,
          n_preflop_iters: int   = 40_000,
          n_episodes:      int   = 1_000,
          n_epochs:        int   = 20,
          batch_size:      int   = 256,
          lr:              float = 1e-3,
          preflop_save:    str   = None,
          discard_save:    str   = None,
          n_workers:       int   = 1):
    """
    Jointly train preflop CFR and DiscardNet in alternating rounds.

    Each round the preflop CFR uses the current discard model for terminal
    values, and the discard model trains on ranges generated by the updated
    preflop strategy.
    """
    from stretegy.discard_cfr.train import generate_episodes

    for r in tqdm(range(1, n_rounds + 1), desc='joint rounds', ncols=80):
        tqdm.write(f'\n── Round {r}/{n_rounds} ─────────────────────────────')

        # Step 1: build terminal_fn from current discard model
        terminal_fn = _make_terminal_fn(discard_model, preflop_model)

        # Step 2: preflop CFR with discard-model terminal values
        tqdm.write(f'[preflop] {n_preflop_iters:,} CFR iters ...')
        preflop_model.train(
            n_iters=n_preflop_iters,
            save_path=preflop_save,
            n_workers=n_workers,
            terminal_fn=terminal_fn,
        )

        # Step 3: generate Deep CFR episodes (advantage net guides current strategy)
        tqdm.write(f'[discard] generating {n_episodes} episodes ...')
        adv_X, adv_Y, str_X, str_Y = generate_episodes(
            preflop_model, discard_model._adv_net, n_episodes)

        # Step 4: train AdvantageNet + StrategyNet
        tqdm.write(f'[discard] training {n_epochs} epochs ...')
        adv_save_r = discard_save.replace('.pt', '_adv.pt') if discard_save else None
        discard_model.train(
            adv_X, adv_Y, str_X, str_Y,
            n_epochs=n_epochs,
            batch_size=batch_size,
            lr=lr,
            adv_save=adv_save_r,
            str_save=discard_save,
        )
